name: PR

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        shell: bash
        run: npm ci

      - name: Run linter
        shell: bash
        run: npm run lint

  vercel:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: sandbox

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Build
        shell: bash
        run: npm run build

      - name: Vercel
        id: vercel
        if: hashFiles('dist/main.js') != ''
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: true
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: 'dist'
